name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'

    - name: Install dependencies
      run: npm install, npm install @nomicfoundation/edr-linux-x64-gnu

    - name: Generate code coverage
      run: npx hardhat coverage
